### ISSUE TITLE
cu5t0mPe0 - The executor takes away all the funds during `setModule`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-arrakis-judging#15]
cu5t0mPe0

high

# The executor takes away all the funds during `setModule`

## Summary

During `setModule`, the executor will call `initializePosition` to deposit funds into the pool. Subsequently, the executor can call `withdraw` to withdraw all the funds.

## Vulnerability Detail

When the executor sets a new module using Vault, they use a `call` to invoke any function of the new module.

According to the sponsor's description, the executor is not trusted, but it is safe for setModule and its related implementations, but in fact this is not the case.

This is because the executor can call the `withdraw` function of the new module through Vault's `setModule` function. Since the call originates from the Vault, `msg.sender` is set to the Vault, bypassing permission restrictions.

Consider the following scenario:

1. A malicious executor calls `initializePosition` to redeposit funds into the pool.
2. Due to the for loop, the malicious executor then calls `ValantisHOTModulePublic.withdraw` to withdraw all funds to a target address. This occurs because `withdraw` is called by the vault, thereby bypassing permission checks.

## Impact

executors can steal all funds

## Code Snippet

https://github.com/sherlock-audit/2024-03-arrakis/blob/64a7dc6ccb5de2824870474a9f35fd3386669e89/arrakis-modular/src/abstracts/ArrakisMetaVault.sol#L130-L130

## Tool used

Manual Review

## Recommendation

We should use a whitelist mechanism to restrict the functions that the executor can call.

Duplicate of #50

**Comment by 0xjuaan** [comment]
Escalate

Valid dupe of #50

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept it and duplicate with #50.

**Comment by WangSecurity** [comment]
Result:
High
Duplicate of #50

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xjuaan](https://github.com/sherlock-audit/2024-03-arrakis-judging/issues/15/#issuecomment-2164027151): accepted
